bundler_args: ""
rvm:
  - 2.0.0
  - 2.1.5
  - 2.2.0
gemfile:
 - gemfiles/rails3.2.gemfile
 - gemfiles/rails4.0.gemfile
 - gemfiles/rails4.1.gemfile
matrix:
  exclude:
    - rvm: 2.2.0
      gemfile: gemfiles/rails3.2.gemfile
script: bundle exec rake spec
